add Honeybadger.event interface
honeybadger-io/honeybadger-elixir pull request #564
Opened 2024-08-28 20:41 UTC by mdg

send application events to the event endpoint
add a timestamp

issue #554
https://github.com/honeybadger-io/honeybadger-elixir/issues/554

2024-08-28 21:17 UTC, stympy approved these changes
This is looking good, thanks! Could you address the `ts` comment and run `mix format`?

2024-08-28 21:17 UTC, stympy commented on lib/honeybadger.ex
> +    Client.send_event(event_data)
Could you supply a `ts` of `DateTime.utc_now()` here if one isn't present in the map?

2024-08-28 22:36 UTC, mdg commented
@stympy thanks for the helpful prompt review. I think those 2 issues should be addressed now.

2024-08-29 12:19 UTC, stympy requested changes
Looking good. I have some [suggested changes](https://github.com/pathpub/honeybadger-elixir/pull/1) for you. :)

2024-08-29 14:13 UTC, stympy approved these changes

2024-08-29 14:17 UTC, merged

2024-08-29 14:41 UTC, stympy commented
Released in 0.22.0. Thanks!

2024-08-30 22:39 UTC, mdg commented
I've upgraded our app back to the main version. Thanks for handling it so quickly!